# Generated by Django 5.2.1 on 2025-05-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="role",
            field=models.CharField(
                choices=[
                    ("backend", "백엔드"),
                    ("frontend", "프론트엔드"),
                    ("designer", "디자이너"),
                    ("full_stack", "풀스택"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("meeting", "모집"), ("project", "프로젝트")], max_length=15
            ),
        ),
    ]
