# Generated by Django 5.2 on 2025-05-13 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="application",
            name="role",
            field=models.CharField(
                choices=[
                    ("designer", "디자이너"),
                    ("backend", "백엔드"),
                    ("frontend", "프론트엔드"),
                ],
                default="backend",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="posts/images/default.png",
                null=True,
                upload_to="posts/images/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="roles",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("project", "프로젝트"), ("study", "스터디")], max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_post"
            ),
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_post_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("post", "date"), name="unique_post_schedule_date"
            ),
        ),
    ]
