# Generated by Django 5.2.1 on 2025-05-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="description",
            new_name="memo",
        ),
    ]
