# Generated by Django 5.2 on 2025-05-10 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="leave_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "대기중"),
                    ("accepted", "수락됨"),
                    ("rejected", "거절됨"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="role",
            field=models.CharField(
                choices=[
                    ("backend", "백엔드"),
                    ("frontend", "프론트엔드"),
                    ("designer", "디자이너"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="대표이미지 프론트에서 파일로 보냄",
                null=True,
                upload_to="posts/images/",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "post")},
        ),
    ]
