# Generated by Django 5.2.1 on 2025-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_description_schedule_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="writer_role",
            field=models.CharField(
                choices=[
                    ("backend", "백엔드"),
                    ("frontend", "프론트엔드"),
                    ("designer", "디자이너"),
                    ("fullstack", "풀스택"),
                ],
                default="backend",
                help_text="작성자의 역할",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
