# Generated by Django 5.2 on 2025-05-12 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "Notification_id",
                    models.AutoField(
                        db_column="Notification_id", primary_key=True, serialize=False
                    ),
                ),
                ("content", models.CharField(db_column="content", max_length=255)),
                (
                    "url",
                    models.CharField(
                        blank=True, db_column="url", max_length=255, null=True
                    ),
                ),
                ("is_read", models.BooleanField(db_column="is_read")),
                ("type", models.CharField(db_column="type", max_length=230)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        db_column="application_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.application",
                    ),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        db_column="ChatMessage_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        db_column="participant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chatroomparticipant",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_column="Post_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.post",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        db_column="schedule_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "db_table": "NOTIFICATION",
            },
        ),
    ]
