# Generated by Django 5.2 on 2025-05-13 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("posts", "0002_alter_post_options_alter_application_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="application",
            field=models.ForeignKey(
                blank=True,
                db_column="application_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.application",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                db_column="Post_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                db_column="schedule_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.schedule",
            ),
        ),
    ]
