# Generated by Django 5.2.1 on 2025-05-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                db_column="participant_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatroomparticipant",
            ),
        ),
    ]
