# Generated by Django 5.2 on 2025-05-14 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="chat_message",
            field=models.ForeignKey(
                blank=True,
                db_column="ChatMessage_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatmessage",
            ),
        ),
    ]
