# Generated by Django 5.2 on 2025-05-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
