# Generated by Django 5.2.1 on 2025-05-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
