# Generated by Django 5.2 on 2025-05-02 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "ChatMessage_id",
                    models.AutoField(
                        db_column="ChatMessage_id", primary_key=True, serialize=False
                    ),
                ),
                ("room_id", models.CharField(db_column="room_id", max_length=100)),
                ("content", models.TextField(db_column="content")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_column="updated_at", null=True),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_column="is_deleted", default=False),
                ),
                (
                    "chat_user",
                    models.ForeignKey(
                        db_column="chat_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "db_table": "ChatMessage",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoomParticipant",
            fields=[
                (
                    "participant_id",
                    models.AutoField(
                        db_column="participant_id", primary_key=True, serialize=False
                    ),
                ),
                ("room_id", models.CharField(db_column="room_id", max_length=100)),
                ("alarm_on", models.BooleanField(db_column="alarm_on", default=True)),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, db_column="joined_at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅방 참여자",
                "db_table": "Chat_room_participant",
            },
        ),
    ]
