name: CI - Quality Checks

on:
  pull_request:
    branches: [dev, main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.2'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
      env:
        POETRY_HOME: $HOME/.poetry

    - name: Set up Poetry path
      run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Install dependencies with Poetry
      run: |
        poetry config virtualenvs.in-project true
        poetry install --no-interaction --no-root

    - name: 🔥 Fail if dev setting is in manage.py
      run: |
        if grep -q "settings.dev" moCOMOco/manage.py; then
          echo "❌ ERROR: You are trying to deploy with dev settings."
          exit 1
        fi

    - name: 1️⃣ Run linter (flake8)
      run: poetry run flake8 .
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: 2️⃣ Run tests (pytest)
      run: poetry run pytest --disable-warnings --maxfail=1 --tb=short

    - name: 3️⃣ Type checking (mypy)
      run: poetry run mypy .

    - name: 5️⃣ Security check (bandit)
      run: poetry run bandit -r . -x tests
