name: CI - Quality Checks

on:
  pull_request:
    branches: [dev, main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Set Python version in pyproject.toml
      run: |
        poetry env use 3.11

    - name: Install dependencies
      run: |
        poetry install

    - name: 🔥 Fail if dev setting is in manage.py
      run: |
        if grep -q "settings.dev" moCOMOco/manage.py; then
          echo "❌ ERROR: You are trying to deploy with dev settings."
          exit 1
        fi

    - name: 🚫 Fail if there are missing migrations
      run: |
        poetry run python moCOMOco/manage.py makemigrations --check --dry-run

    - name: 5️⃣ Security check (bandit)
      run: |
        poetry run pip install bandit
        poetry run bandit -r .
